### Alvaro José Bolaños Vega
### A00838866

## M1 Actividad 5

In [2]:
import numpy as np
import pandas as pd

# **Ejercicio 1 (Numpy)**
1.- Crear un vector “x” con 10 ceros y mostrarlo.<br>
2.- Modificar el quinto elemento del vector x para que su valor sea 3.<br>
3.- Crear un vector “y” con valores del 1 al 20, de 1 en 1. Utiliza la función arange.<br>
4.- Crear un vector “z” con valores del 1 al 20, de 2 en 2.<br>
5.- Crear una matriz w de 3x2, con valores iniciales en 0.<br>
6.- Modificar el elemento en la posición 2,2 de la matriz w para que su valor sea 5.<br>
7.- Crear un vector de 5 elementos, con valores aleatorios enteros entre 1 y 10.<br>
8.- Crear el arreglo x1 de la lista [1,2,3]<br>
9.-  Sumar 10 a cada elemento del vector<br>

In [16]:
# 1.
x = np.zeros(10)
print(x)

# 2.
x[4] = 3
print(x)

# 3.
y = np.arange(1, 20)
print(y)

# 4.
z = np.arange(1, 20, 2)
print(z)

# 5.
w = np.zeros((3, 2))
print(w)

# 6.
w[1,1] = 5
print(w)

# 7.
rand = np.random.uniform(1, 10, 5)
print(rand)

# 8.
x1 = np.array([1, 2, 3])
print(x1)

# 9.
x1 += 10
print(x1)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 3. 0. 0. 0. 0. 0.]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0. 0.]
 [0. 5.]
 [0. 0.]]
[9.00038735 4.72737802 4.5922806  4.17081683 3.1465996 ]
[1 2 3]
[11 12 13]


# **Ejercicio 2**

El archivo titanic.csv   contiene información sobre los pasajeros del Titanic. Escribir un programa con los siguientes requisitos:

<ul>
<li>Generar un DataFrame con los datos del archivo.</li>
<li>Mostrar por pantalla las dimensiones del DataFrame, el número de datos que contiene, los nombres de sus columnas, los tipos de datos de las columnas, las 10 primeras filas y las 10 últimas filas</li>
<li>Mostrar por pantalla los datos del pasajero con identificador 148.</li>
<li>Mostrar por pantalla las filas pares del DataFrame.</li>
<li>Mostrar por pantalla los nombres de las personas que iban en primera clase ordenadas alfabéticamente.</li>
<li>Mostrar por pantalla el porcentaje de personas que sobrevivieron y murieron.</li>
<li>Mostrar por pantalla el porcentaje de personas que sobrevivieron en cada clase.</li>
<li>Eliminar del DataFrame los pasajeros con edad desconocida.</li>
<li>Mostrar por pantalla la edad media de las mujeres que viajaban en cada clase.</li>
<li>Añadir una nueva columna booleana para ver si el pasajero era menor de edad o no.</li>
<li>Mostrar por pantalla el porcentaje de menores y mayores de edad que sobrevivieron en cada clase.</li>
</ul>

In [ ]:
# Importar titanic-1.csv
titanic = pd.read_csv('titanic-1.csv')

# Generar Dataframe
df = pd.DataFrame(titanic)

# # Mostrar df
# print(df.shape)
# print(df.size)
# print(df.columns)
# # data type of each column
# print(df.dtypes)

# # Mostrar las primeras 10 filas
# print(df.head(10))

# # Mostrar las últimas 10 filas
# print(df.tail(10))

# # Datos pasajero 148
# print(df.loc[148])

# # Filas pares
# print(df.iloc[::2])

# # Nombres de passajeros con columna Pclass = 1 alfabeticamnete
# print(df[df['Pclass'] == 1]['Name'].sort_values())

# # Porcentaje de sobrevivientes (Survived = 1)
# print(df['Survived'].mean())

# # Porcentaje de muertos
# print(1 - df['Survived'].mean())

# # Promedio sobrevivientes por clase
# print(df.groupby('Pclass')['Survived'].mean())

# Eliminar pasajeros con edad NaN
df = df.dropna(subset=['Age'])

# Edad media de mujeres por clase
print(df.groupby('Pclass')['Age'].mean())

# Añadir columna 'OfAge' con valor True si la edad es mayor a 18
df['OfAge'] = df['Age'] > 18

# Porcentaje de sobrevientes mayores de edad por clase
print(df[df['OfAge']].groupby('Pclass')['Survived'].mean())

# Porcentaje de sobrevivientes menores de edad por clase
print(df[~df['OfAge']].groupby('Pclass')['Survived'].mean())




Pclass
1    38.233441
2    29.877630
3    25.140620
Name: Age, dtype: float64
     PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
885          886         0       3   
886          887         0       2   
887          888         1       1   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0  