### Alvaro José Bolaños Vega
### A00838866

## M1 Actividad 5

In [2]:
import numpy as np
import pandas as pd

# **Ejercicio 1 (Numpy)**
1.- Crear un vector “x” con 10 ceros y mostrarlo.<br>
2.- Modificar el quinto elemento del vector x para que su valor sea 3.<br>
3.- Crear un vector “y” con valores del 1 al 20, de 1 en 1. Utiliza la función arange.<br>
4.- Crear un vector “z” con valores del 1 al 20, de 2 en 2.<br>
5.- Crear una matriz w de 3x2, con valores iniciales en 0.<br>
6.- Modificar el elemento en la posición 2,2 de la matriz w para que su valor sea 5.<br>
7.- Crear un vector de 5 elementos, con valores aleatorios enteros entre 1 y 10.<br>
8.- Crear el arreglo x1 de la lista [1,2,3]<br>
9.-  Sumar 10 a cada elemento del vector<br>

In [16]:
# 1.
x = np.zeros(10)
print(x)

# 2.
x[4] = 3
print(x)

# 3.
y = np.arange(1, 20)
print(y)

# 4.
z = np.arange(1, 20, 2)
print(z)

# 5.
w = np.zeros((3, 2))
print(w)

# 6.
w[1,1] = 5
print(w)

# 7.
rand = np.random.uniform(1, 10, 5)
print(rand)

# 8.
x1 = np.array([1, 2, 3])
print(x1)

# 9.
x1 += 10
print(x1)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 3. 0. 0. 0. 0. 0.]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0. 0.]
 [0. 5.]
 [0. 0.]]
[9.00038735 4.72737802 4.5922806  4.17081683 3.1465996 ]
[1 2 3]
[11 12 13]
